Miglioramento delle performance
F-S-C/StrumentalMente pull request #12
Opened 2019-04-12 10:26 UTC by espositoandrea

Drastico miglioramento delle _performance_ ottenuto tramite una _(quasi)_ totale riscrittura del codice sorgente.

2019-04-12 14:09 UTC, Ax3lFernus approved these changes
Errori e Bug riscontrati:
- Quando viene completato il quiz della **Teoria del Pianofote** e si tenta di verificarlo, una volta arrivato all'ultima domanda, la pressione del pulsante "Esci" mostra una pagina bianca. [_Risolto_ ]
-  Quando viene completato il quiz della **Teoria della Batteria** e si tenta di verificarlo, una volta arrivato all'ultima domanda, la pressione del pulsante "Esci" mostra la lista degli argomenti a schermo intero. [_Risolto_ ]
-  Le pagine **Informazioni** e **Aiuto** sono sproporzionate rispetto alle dimensioni dello schermo.

2019-04-12 14:12 UTC, espositoandrea commented
> * Le pagine **Informazioni** e **Aiuto** sono sproporzionate rispetto alle dimensioni dello schermo.

@Ax3lFernus sono spoporzionate in altezza o larghezza? Puoi pubblicare uno screenshot?

2019-04-12 14:16 UTC, Ax3lFernus requested changes
- Le pagine **Informazioni** e **Aiuto** sono sproporzionate in larghezza rispetto alle dimensioni dello schermo.
- Gli avvisi del "_mancato completamento della teoria_" dovrebbero essere mostrati **meno** di frequente.
- Il testo presente all'interno dell'avviso che chiede conferma del _reset del profilo_ dovrebbe avere più margine rispetto ai bordi sinistro e destro.
- L'immagine del basso, nella sezione **Strumenti**, è sproporzionata rispetto alle immagini degli altri strumenti.

_EDIT_
Allego screenshot del problema elencato al primo punto:
![Screen](https://user-images.githubusercontent.com/21280026/56044064-b5be1680-5d3e-11e9-9ab6-2ab931a6a440.png)

2019-04-12 15:08 UTC, espositoandrea commented
Stando al [commento](https://github.com/F-S-C/StrumentalMente/pull/12#pullrequestreview-226105955) di @Ax3lFernus, ho stilato una lista delle attività da completare per risolvere i problemi da lui segnalati.

# TODO

- [ ] Ridimensionare le pagine pop-up (automaticamente)
- [ ] Ridimensionare l'immagine del basso nella sezione strumenti
- [ ] Aumentare i margini nel dialogo di reset del profilo

Si noti che non è stata presa in considerazione la riduzione delle richieste di conferma di prosecuzione in quanto requisito funzionale già concordato.

2019-04-12 15:21 UTC, Ax3lFernus commented
> Stando al [commento](https://github.com/F-S-C/StrumentalMente/pull/12#pullrequestreview-226105955) di @Ax3lFernus, ho stilato una lista delle attività da completare per risolvere i problemi da lui segnalati.
> 
> # TODO
> * [x]  Ridimensionare le pagine pop-up (automaticamente)
> * [x]  Ridimensionare l'immagine del basso nella sezione strumenti
> * [ ]  Aumentare i margini nel dialogo di reset del profilo
> 
> Si noti che non è stata presa in considerazione la riduzione delle richieste di conferma di prosecuzione in quanto requisito funzionale già concordato.
> 
> ## Edit 1
> Commit [81d5089](https://github.com/F-S-C/StrumentalMente/commit/81d50899336a83004b3486e1a606209568d9e92b): aggiunto il ridimensionamento automatico delle pagine pop-up in base allo schermo dell'utente.
> 
> ## Edit 2
> Commit [2308937](https://github.com/F-S-C/StrumentalMente/commit/2308937228e30b4c89fb021e8a903df5fa5142cf): corrette le dimensioni delle immagini nelle card (tra cui quella del basso nella sezione strumenti)

Il problema della card persiste. Allego screenshot:
![screen-card](https://user-images.githubusercontent.com/21280026/56048225-51538500-5d47-11e9-8b0a-7de12e465b86.PNG)

2019-04-12 15:43 UTC, espositoandrea commented
> @Ax3lFernus:
> [...]
> * Riguardo le modifiche effettuate nell'_Edit 1_: E' presente un alert (immagino per scopi di debug) quando si aprono i pop-up. L'alert è presente nel file: `.\src\assets\js\render.js` alla riga nr._394_.
> * Riguardo le modifiche effettuate nell'_Edit 2_: Il problema della card persiste. Allego screenshot:
>   ![screen-card](https://user-images.githubusercontent.com/21280026/56048225-51538500-5d47-11e9-8b0a-7de12e465b86.PNG)

Gli errori segnalati sono stati corretti nel commit cab59444603a89cfe61ae21841651bfac9324049.

2019-04-12 15:44 UTC, Ax3lFernus approved these changes

2019-04-12 15:51 UTC, espositoandrea commented
Si è effettuato il merge della branch `master` nella branch `improve-performance` per risolvere i conflitti di merge.

2019-04-12 16:31 UTC, espositoandrea commented
Tutte le pagine degli accordi presentano dei problemi a livello di padding: vi hanno un valore maggiore rispetto alle altre pagine del sistema.

2019-04-12 16:35 UTC, Ax3lFernus commented
> Tutte le pagine degli accordi presentano dei problemi a livello di padding: vi hanno un valore maggiore rispetto alle altre pagine del sistema.
- C'è un errore nella visualizzazione delle figures negli accordi:
![errore_visualizzazione_immagini_accordi](https://user-images.githubusercontent.com/21280026/56052421-a8f6ee00-5d51-11e9-9aa1-af73153b7f2d.PNG)

2019-04-12 16:40 UTC, espositoandrea commented
> > Tutte le pagine degli accordi presentano dei problemi a livello di padding: vi hanno un valore maggiore rispetto alle altre pagine del sistema.
> 
> * C'è un errore nella visualizzazione delle figures negli accordi:
>   ![errore_visualizzazione_immagini_accordi](https://user-images.githubusercontent.com/21280026/56052421-a8f6ee00-5d51-11e9-9aa1-af73153b7f2d.PNG)

È un problema legato a quello del padding: risolvendo il primo si risolverà automaticamente anche il secondo.

2019-04-12 16:48 UTC, espositoandrea commented
I problemi segnalati nei seguenti commenti:

- https://github.com/F-S-C/StrumentalMente/pull/12#issuecomment-482639388 (by @espositoandrea)
- https://github.com/F-S-C/StrumentalMente/pull/12#issuecomment-482640564 (by @Ax3lFernus)
- https://github.com/F-S-C/StrumentalMente/pull/12#issuecomment-482642291 (by @espositoandrea)

Sono stati corretti nel commit b75e86af3cbe66e4db7968307ce0d010dc499ccc.

2019-04-12 17:00 UTC, Ax3lFernus reviewed
Ulteriori errori riscontrati:
- Il pulsante "_Torna alla home_" di tutti i quiz, mostra la navbar con una pagina bianca. (Allego immagine)
![image](https://user-images.githubusercontent.com/21280026/56053274-fc6a3b80-5d53-11e9-84b4-c991fad6fae1.png)
- Nei quiz, non è possibile chiudere l'applicazione né dal "close button" né dal pulsante "Esci". 
- Dopo vari minuti di utilizzo, nella consolle appare il seguente errore: 
`(node:10608) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 maximize listeners added. Use emitter.setMaxListeners() to increase limit`

2019-04-12 17:06 UTC, espositoandrea commented
# TODO

- [ ] Correzione dei bottoni "torna alla home" dei quiz
- [ ] Correzione dei bottoni per la chiusura dei quiz
- [ ] Correzione dei bottoni della navbar (esempio: selezionando `Accordi & rarr; Chitarra` e ricliccando su `Accordi` non avviene nulla, ma si dovrebbe tornare alla lista degli strumenti)

@Ax3lFernus per il problema per cui nella console sono segnalati troppi EventEmitter da Node.js è meglio creare una issue.

2019-04-13 11:44 UTC, espositoandrea commented
Si è effettuato il merge della branch `master` per risolvere i conflitti.

2019-04-13 12:19 UTC, montanarograziano approved these changes

2019-04-13 16:06 UTC, Ax3lFernus requested changes
Come segnalato da @prewarning il pulsante `close-button` (a.k.a. times o "x") non funziona in nessuna delle pagine.

2019-04-13 19:17 UTC, espositoandrea commented
> Come segnalato da @prewarning il pulsante `close-button` (a.k.a. times o "x") non funziona in nessuna delle pagine.

L'errore è stato corretto nel commit 4603991c2d55441ef7ebd56b4d9971be0dc56ae7.

2019-04-14 08:02 UTC, Ax3lFernus commented
> > Come segnalato da @prewarning il pulsante `close-button` (a.k.a. times o "x") non funziona in nessuna delle pagine.
> 
> L'errore è stato corretto nel commit [4603991](https://github.com/F-S-C/StrumentalMente/commit/4603991c2d55441ef7ebd56b4d9971be0dc56ae7).
# Errore persistente
**Attenzione**: L'errore **persiste**, nonostante il tentativo di correzione effettuato nel commit [`4603991`](https://github.com/F-S-C/StrumentalMente/commit/4603991c2d55441ef7ebd56b4d9971be0dc56ae7).

Il click del "_close button_" funziona al più una volta e nelle pagine _Landing_ e _Home_. 

Ho notato che, in più di un caso, si deve procedere a cliccare continuativamente il bottone in modo da rendere visibile il Pop-up di uscita. 

## Azioni da intraprendere in caso di mancata correzione
Data la persistenza dell'errore, intraprenderò una delle seguenti strade:
- Se l'errore continuerà a persistere, sarà mia premura aprire una **Issue**, in modo da avere il tempo per la correzione dello stesso anche successivamente al _merge_ della branch.
- Se verrà corretto, procederò ad approvare la _pull request_.

2019-04-14 11:20 UTC, espositoandrea commented
L'errore dovrebbe ora esser stato risolto dal commit 5affc04b6a240ba535c9ebd9793e1de631115ae2. Sembrava esser dovuto a delle chiamate mal definite della funzione `require` di _Node.js_.

2019-04-14 12:58 UTC, Ax3lFernus approved these changes

2019-04-15 07:28 UTC, ReginaZaccaria commented
Problemi ritrovati:

- Ridurre le dimensioni delle card [HOME]
- Lo scrolling prende tutto il lato destro delle pagine arrivando fino al "close-button"
- Nella pagina "suono" [TEORIA/BASE] si attiva lo scrolling per la dimensione del testo. Stesso problema è risultato in molte altre pagine.
- Nella pagina "chiavi" e "valori e pause" [TEORIA/BASE] i simboli non sono visibili. Stesso problema è risultato nella pagina "alterazioni" [TEORIA/AVANZATA]
- Il bottone del "torna all'elenco del ..." è da ridimensionare nella parte degli ACCORDI
- Le short-cut ALT+S *, ALT+A * non funzionano.

2019-04-15 07:30 UTC, ReginaZaccaria requested changes
Problemi ritrovati:

- Ridurre le dimensioni delle card [HOME]
- Lo scrolling prende tutto il lato destro delle pagine arrivando fino al "close-button"
- Nella pagina "suono" [TEORIA/BASE] si attiva lo scrolling per la dimensione del testo. Stesso problema è risultato in molte altre pagine.
- Nella pagina "chiavi" e "valori e pause" [TEORIA/BASE] i simboli non sono visibili. Stesso problema è risultato nella pagina "alterazioni" [TEORIA/AVANZATA]
- Il bottone del "torna all'elenco del ..." è da ridimensionare nella parte degli ACCORDI
- Le short-cut ALT+S *, ALT+A * non funzionano.

2019-04-15 16:45 UTC, espositoandrea commented
> Problemi ritrovati: [...]

Si riporta la lista di problemi segnalata da @ReginaZaccaria sotto forma di ToDo List, in modo da poter facilmente traccia dei problemi risolti da risolvere. Si editerà il seguente commento riportando man mano le modifiche effettuate.

- [ ] Ridurre le dimensioni delle card [HOME]
- [ ] Lo scrolling prende tutto il lato destro delle pagine arrivando fino al "close-button"
- [ ] Nella pagina "suono" [TEORIA/BASE] si attiva lo scrolling per la dimensione del testo. Stesso problema è risultato in molte altre pagine.
- [ ] Nella pagina "chiavi" e "valori e pause" [TEORIA/BASE] i simboli non sono visibili. Stesso problema è risultato nella pagina "alterazioni" [TEORIA/AVANZATA]
- [ ] Il bottone del "torna all'elenco del ..." è da ridimensionare nella parte degli ACCORDI
- [ ] Le short-cut ALT+S *, ALT+A * non funzionano.

2019-04-17 10:27 UTC, Davidedes approved these changes

2019-04-18 16:03 UTC, Ax3lFernus requested changes
Il programma, una volta compilato per la distribuzione e installato, non risponde ai comandi nella _landing page_ rendendo il programma inutilizzabile (e non terminabile, dato che anche il pulsante _close-button_ non risponde).

2019-04-19 12:55 UTC, Ax3lFernus requested changes
### Errore persistente
Una volta installata l'app, il pulsante **INIZIA**, presente nella _landing page_, non risponde ai comandi. 
Si è effettuato un tentativo per raggiungere la _home_ tramite il tasto _Invio_ ma, anch'esso, si è rivelato inutile.
Il problema non sussiste, invece, per i pulsanti "di sistema" presenti in alto a destra che, adesso, rispondono correttamente ai comandi.

2019-04-19 14:06 UTC, espositoandrea commented
> ### Errore persistente
> Una volta installata l'app, il pulsante **INIZIA**, presente nella _landing page_, non risponde ai comandi.
> Si è effettuato un tentativo per raggiungere la _home_ tramite il tasto _Invio_ ma, anch'esso, si è rivelato inutile.
> Il problema non sussiste, invece, per i pulsanti "di sistema" presenti in alto a destra che, adesso, rispondono correttamente ai comandi.

@Ax3lFernus puoi postare uno screenshot della console di Chromium per rendere chiaro il motivo dell'errore? Ho inserito la shortcut `CTRL+SHIFT+I` per aprire la suddetta console.

2019-04-20 11:25 UTC, prewarning commented
**Errori ritrovati in data 20/04/2019**

- L'applicazione una volta aperta presenta una doppia scroll-bar nella parte destra dello schermo.
- Una volta entrati in una pagina della sezione Teoria, è impossibile ritornare nella pagina principale di Teoria, né tramite pulsante né tramite shortcut.
- Le pagine a finestra modale ( Aiuto,Mappa, Credits) presentano bug grafici:
       1. La loro titlebar scrolla in relazione al frame principale di StrumentalMente.
       2. Se si riduce il frame principale, e si aprono le due pagine, esse appariranno "tagliate".
       3. Non è possibile ridimensionarle; si può solo ridimensionare il frame principale per far rientrare le 
           due pagine all'interno di esso, ottenendo però il bug 2.
-

2019-04-20 11:27 UTC, montanarograziano requested changes
**Errori ritrovati in data 20/04/2019**

- L'applicazione una volta aperta presenta una doppia scroll-bar nella parte destra dello schermo.
- Una volta entrati in una pagina della sezione Teoria, è impossibile ritornare nella pagina principale di Teoria, né tramite pulsante né tramite shortcut.
- Le pagine a finestra modale ( Aiuto,Mappa, Credits) presentano bug grafici:
       1. La loro titlebar scrolla in relazione al frame principale di StrumentalMente.
       2. Se si riduce il frame principale, e si aprono le due pagine, esse appariranno "tagliate".
       3. Non è possibile ridimensionarle; si può solo ridimensionare il frame principale per far rientrare le 
           due pagine all'interno di esso, ottenendo però il bug 2.

2019-04-20 12:53 UTC, Ax3lFernus requested changes
## Controllo della console di Chromium
In base a quanto richiesto da @espositoandrea, ho tentato di controllare la console di Chromium per verificare i problemi che riguardavano l'impossibilità di entrare nell'applicazione dal pulsante **INIZIA**.
### Errori all'apertura dell'Applicazione
Una volta aperta l'applicazione, è possibile notare (fin da subito) la mancanza dei font (non presenti nel sistema) utilizzati per lo sviluppo della stessa. Aprendo la console, è palese la loro mancanza infatti, Chromium stesso, lancia svariati errori a riguardo:
![Apertura_App](https://user-images.githubusercontent.com/21280026/56457449-706f9980-637b-11e9-96c3-60155e9f338e.PNG)
Inoltre è possibile notare la mancanza dei font anche dal pop-up di chiusura:
![Font Non presenti](https://user-images.githubusercontent.com/21280026/56457476-c7756e80-637b-11e9-8b46-74cbd6900f12.PNG)
### Impossibilità di "entrare" nell'Applicazione
Rigurado al pulsante "INIZIA", allego (come richiesto) lo screenshot dell'errore mostrato in console:
![POST_PREMO_BOTTONE](https://user-images.githubusercontent.com/21280026/56457473-b7f62580-637b-11e9-8808-877e2ac869ca.PNG)
**N.B:** Il medesimo errore si presenta quando si tenta di accedere alla _home_ tramite il pulsante _invio_.

2019-04-20 12:59 UTC, espositoandrea commented
> ## Controllo della console di Chromium
> In base a quanto richiesto da @espositoandrea, ho tentato di controllare la console di Chromium per verificare i problemi che riguardavano l'impossibilità di entrare nell'applicazione dal pulsante **INIZIA**.
> 
> ### Errori all'apertura dell'Applicazione
> Una volta aperta l'applicazione, è possibile notare (fin da subito) la mancanza dei font (non presenti nel sistema) utilizzati per lo sviluppo della stessa. Aprendo la console, è palese la loro mancanza infatti, Chromium stesso, lancia svariati errori a riguardo:
> ![Apertura_App](https://user-images.githubusercontent.com/21280026/56457449-706f9980-637b-11e9-96c3-60155e9f338e.PNG)
> Inoltre è possibile notare la mancanza dei font anche dal pop-up di chiusura:
> ![Font Non presenti](https://user-images.githubusercontent.com/21280026/56457476-c7756e80-637b-11e9-8b46-74cbd6900f12.PNG)
> 
> ### Impossibilità di "entrare" nell'Applicazione
> Rigurado al pulsante "INIZIA", allego (come richiesto) lo screenshot dell'errore mostrato in console:
> ![POST_PREMO_BOTTONE](https://user-images.githubusercontent.com/21280026/56457473-b7f62580-637b-11e9-8808-877e2ac869ca.PNG)
> **N.B:** Il medesimo errore si presenta quando si tenta di accedere alla _home_ tramite il pulsante _invio_.

I problemi dovrebbero essere stati risolti nel commit 3be11a2dbc13a43bfabe0b5c76514297bf2f7efd.

2019-04-20 13:04 UTC, Ax3lFernus requested changes
## Errore durante la creazione del file di installazione
Allego screenshot della console:
![image](https://user-images.githubusercontent.com/21280026/56457594-68b0f480-637d-11e9-9c61-82dec5272306.png)
**N.B:** Ho eseguito anche il comando `make install` prima di avviare il comando `make deploy` ma la situazione è rimasta invariata.

2019-04-20 13:05 UTC, espositoandrea commented
> **Errori ritrovati in data 20/04/2019**
> 
> * L'applicazione una volta aperta presenta una doppia scroll-bar nella parte destra dello schermo.
> * Una volta entrati in una pagina della sezione Teoria, è impossibile ritornare nella pagina principale di Teoria, né tramite pulsante né tramite shortcut.
> * Le pagine a finestra modale ( Aiuto,Mappa, Credits) presentano bug grafici:
>   1. La loro titlebar scrolla in relazione al frame principale di StrumentalMente.
>   2. Se si riduce il frame principale, e si aprono le due pagine, esse appariranno "tagliate".
>   3. Non è possibile ridimensionarle; si può solo ridimensionare il frame principale per far rientrare le
>   due pagine all'interno di esso, ottenendo però il bug 2.

Si è corretto l'errore dello scrolling della titlebar nel commit 2e1df0475be612fea0230e2335990dfb6f37fa1c

2019-04-20 13:07 UTC, espositoandrea commented
> ## Errore durante la creazione del file di installazione
> Allego screenshot della console:
> ![image](https://user-images.githubusercontent.com/21280026/56457594-68b0f480-637d-11e9-9c61-82dec5272306.png)
> **N.B:** Ho eseguito anche il comando `make install` prima di avviare il comando `make deploy` ma la situazione è rimasta invariata.

@Ax3lFernus è necessario installare lo script css_html_js_minify di python eseguendo questo comando:

```
pip install css-html-js-minify
```

Le dipendenze degli script Python non fanno parte del `Makefile`.

2019-04-20 14:26 UTC, Ax3lFernus requested changes
Adesso il pulsante **INIZIA** funziona in modo corretto ma il resto dell'Applicazione non risponde ai comandi, compresi i pulsanti "di sistema", fatta eccezione per il pulsante di "Ricarica - Debug".

2019-04-20 14:30 UTC, espositoandrea commented
> **Errori ritrovati in data 20/04/2019**
> 
> * L'applicazione una volta aperta presenta una doppia scroll-bar nella parte destra dello schermo.
> * Una volta entrati in una pagina della sezione Teoria, è impossibile ritornare nella pagina principale di Teoria, né tramite pulsante né tramite shortcut.
> * Le pagine a finestra modale ( Aiuto,Mappa, Credits) presentano bug grafici:
>   1. La loro titlebar scrolla in relazione al frame principale di StrumentalMente.
>   2. Se si riduce il frame principale, e si aprono le due pagine, esse appariranno "tagliate".
>   3. Non è possibile ridimensionarle; si può solo ridimensionare il frame principale per far rientrare le
>   due pagine all'interno di esso, ottenendo però il bug 2.

Con il commit e94c9d34789f39256ed88f558a3020ba1ac387c6 i popup si ridimensionano automaticamente.

2019-04-20 15:00 UTC, espositoandrea commented
> **Errori ritrovati in data 20/04/2019**
> 
> * L'applicazione una volta aperta presenta una doppia scroll-bar nella parte destra dello schermo.
> * Una volta entrati in una pagina della sezione Teoria, è impossibile ritornare nella pagina principale di Teoria, né tramite pulsante né tramite shortcut.
> * Le pagine a finestra modale ( Aiuto,Mappa, Credits) presentano bug grafici:
>   1. La loro titlebar scrolla in relazione al frame principale di StrumentalMente.
>   2. Se si riduce il frame principale, e si aprono le due pagine, esse appariranno "tagliate".
>   3. Non è possibile ridimensionarle; si può solo ridimensionare il frame principale per far rientrare le
>   due pagine all'interno di esso, ottenendo però il bug 2.

Si può ora (commit e67dc9afc79a8532217dc51f9cc8f29b8e0294a2) tornare all'indice della pagina "teoria" mediante la navbar.

@prewarning con questo sono terminati gli errori segnalati

2019-04-20 15:33 UTC, espositoandrea commented
> Adesso il pulsante **INIZIA** funziona in modo corretto ma il resto dell'Applicazione non risponde ai comandi, compresi i pulsanti "di sistema", fatta eccezione per il pulsante di "Ricarica - Debug".

@Ax3lFernus col commit 5a5d4dbf36f457ef2586815141d2184d0159b090 dovrebbe esser stato risolto l'errore (benché in modo sporco). Se le modifiche funzionano, si cercherà un _workaround_.

Potrebbe essere necessario installare lo script `jsmin` di python, tramite il seguente comando:

```
pip install jsmin
```

2019-04-20 15:58 UTC, Ax3lFernus requested changes
## Problema risolto
Il problema descritto nel mio post [precedente](https://github.com/F-S-C/StrumentalMente/pull/12/#pullrequestreview-228877222) risulta corretto. Tutte le pagine funzionano a dovere.
## I font continuano a non caricarsi correttamente
I font continuano a non essere caricati. L'errore che si visualizza sulla console (mostrato nel mio post [precedente](https://github.com/F-S-C/StrumentalMente/pull/12/#pullrequestreview-228877222)) risulta invariato.

2019-04-20 17:54 UTC, espositoandrea commented
@Ax3lFernus l'errore dei font è stato corretto nel commit e40c590ae05fffdab708d1abfd0e6ebe86bc2379. Era dovuto a una minimizzazione dei file CSS errata.

2019-04-20 18:57 UTC, espositoandrea commented
Nel commit 7f8a078e8cc5e8b7f9c37df47bbe0c5e041bbc44 si è variato lo script `minify.html` migliorando le modifiche apportate nel commit 5a5d4dbf36f457ef2586815141d2184d0159b090.

Potrebbe essere necessario dover installare `htmlmin` per Python mediante il seguente comando:

```
pip install htmlmin
```

Si è rimossa la dipendenza da `css_html_js_minify`.

2019-04-20 18:59 UTC, espositoandrea commented
Se non si riceve alcuna segnalazione di problemi entro l'inizio della giornata di domani (21/04/2019), si assume che questa Pull Request sia pronta per essere chiusa mediante _merge_.

2019-04-20 19:15 UTC, montanarograziano approved these changes
I problemi presentati risultano risolti. 
Non sono stati rilevati ulteriori problemi inerenti alla branch.

2019-04-20 21:24 UTC, Ax3lFernus requested changes
## Errori riscontrati
- Nelle pagine che mostrano gli indici degli argomenti sottoforma di "macro sezioni", quando si tenta di visualizzare l'indice degli argomenti, al click su una delle sezioni, l'applicazione mostra l'animazione ma non la termina in modo corretto. Lo stesso errore è presente nelle pagine degli accordi.
Allego errore mostrato nella console: 
`Uncaught TypeError: Cannot read property 'style' of undefined
    at hideSubButtons (VM108 main.js:44)
    at showSubButtons (VM108 main.js:46)
    at window.parent.warnIfIncomplete (argomenti.html:1)
    at HTMLButtonElement.callback (VM99 render.js:3)`.
- L'accordo del piano "Do maggiore", non mostra correttamente lo schema.
- Nei quiz, quando si procede alla verifica di un argomento e ci si sposta con la tastiera, l'ultima domanda da verificare viene mostrata per una frazione di secondo facendo, di fatto, uscire l'utente dalla verifica del quiz.
- Quando si clicca il pulsante _Torna alla home_ da uno qualsiasi dei quiz, si verifica la seguente situazione:
![image](https://user-images.githubusercontent.com/21280026/56462510-953c2f00-63c4-11e9-98df-556f4cb1f5cf.png)

2019-04-20 21:37 UTC, ReginaZaccaria commented
Errori rilevati:

- Difficoltà nel ridurre i pop-up di grandi dimensioni
- A una precisa combinazione di comandi da tastiera, i bottoni e i tasti (avanti/indietro) non funzionano, mentre le altre short cut funzionano correttamente.

2019-04-20 21:39 UTC, ReginaZaccaria approved these changes

2019-04-20 23:03 UTC, espositoandrea commented
Nel commit 4be3922301727255c3c75ddb3852a7254ec69e6d sono stati corretti gli errori segnalati da @Ax3lFernus nel [suo commento](https://github.com/F-S-C/StrumentalMente/pull/12#pullrequestreview-228891425).

Si riporta la parte finale della descrizione del commit:

> Per problemi nella minimizzazione del JavaScript e dell'HTML si è momentaneamente disattivata tale porzione dello script `minify.py`.

2019-04-21 08:40 UTC, Ax3lFernus requested changes
- Il pulsante "Torna alla home" nei quiz degli accordi e nei quiz di tutti gli strumenti rimanda all'indice degli argomenti della _Teoria_.
- L'immagine dello schema dell'accordo del piano di _Do Maggiore_ non viene mostrata in modo corretto:
![DOMaj-Piano](https://user-images.githubusercontent.com/21280026/56467641-d6166100-6421-11e9-8e12-1974f2d4a8de.PNG)

2019-04-21 08:52 UTC, espositoandrea commented
@Ax3lFernus sono stati corretti tutti gli errori tranne quello dell'accordo di Do. Purtroppo (pur avendo testato dopo aver eseguito `make deploy`) l'errore non appare sulla mia macchina. Infatti l'accordo di Do maggiore appare in questo modo:

![image](https://user-images.githubusercontent.com/23329364/56467765-6903cb00-6423-11e9-9a0f-e8afe3f94671.png)

Se è l'unico errore riscontrabile, ignorarlo momentaneamente: se dovesse continuare a presentarsi dopo le ultime modifiche e su più macchine, allora si provvederà alla creazione di una issue.

2019-04-21 08:53 UTC, espositoandrea commented
Se non si riceve alcuna segnalazione di problemi entro l'inizio della giornata odierna (<time datetime="2019-04-21 13:00"><strong>21 Aprile 2019, ore 13:00</strong></time>), si assume che questa Pull Request sia pronta per essere chiusa mediante _merge_, in quanto stata già più volte testata.

2019-04-21 09:07 UTC, Ax3lFernus requested changes
L'errore sul redirect dei quiz si è (in parte) corretto. "Tornando alla home" dalla pagina dai quiz di uno degli strumenti si verifica il seguente errore:
![image](https://user-images.githubusercontent.com/21280026/56467916-715d0580-6425-11e9-9986-5db704143e20.png)
**N.B:** Lo stesso errore si verifica nei quiz degli accordi.

2019-04-21 09:31 UTC, Ax3lFernus approved these changes

2019-04-21 09:36 UTC, Davidedes approved these changes

2019-04-21 09:40 UTC, espositoandrea commented
In seguito all'approvazione di tutti i membri del team @F-S-C/strumentalmente, si procede con la chiusura di questa PR tramite merge con la branch `master`.

2019-04-21 09:40 UTC, merged